name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  filepond:
    path: ../../packages/filepond
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  awesome_dio_interceptor: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
